[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && rm -rf .expo && rm -rf node_modules/.cache && rm -rf dist && rm -rf web-build && node build-final.js"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  BABEL_ENV = "production"
  SKIP_PREFLIGHT_CHECK = "true"
  EXPO_PLATFORM = "web"
  EXPO_PUBLIC_USE_STATIC = "true"
  EXPO_USE_STATIC = "true"
  EXPO_NO_METRO = "1"
  EXPO_USE_WEBPACK = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200