[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npx expo install --fix && npm run build:web"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  EXPO_USE_FAST_RESOLVER = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200