[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build:web"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  EXPO_USE_FAST_RESOLVER = "1"
  SKIP_PREFLIGHT_CHECK = "true"
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200