[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && rm -rf .expo && rm -rf node_modules/.cache && rm -rf dist && node build-alternative.js"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  BABEL_ENV = "web"
  SKIP_PREFLIGHT_CHECK = "true"
  EXPO_USE_FAST_RESOLVER = "true"
  EXPO_NO_DOTENV = "1"
  EXPO_CLEAR_CACHE = "true"
  EXPO_PLATFORM = "web"
  EXPO_PUBLIC_USE_STATIC = "true"
  EXPO_NO_METRO_LAZY = "1"
  EXPO_NO_FLIPPER = "1"
  EXPO_USE_METRO_REQUIRE = "true"
  EXPO_NO_IMPORT_META = "true"
  EXPO_USE_STATIC = "true"
  EXPO_SKIP_MANIFEST_VALIDATION_WARNINGS = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  EXPO_WEB_BUILD_CACHE = "false"
  EXPO_NO_METRO_TERMINAL_REPORTER = "true"
  METRO_NO_TERMINAL_REPORTER = "true"
  METRO_NO_TERMINAL = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200