[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && rm -rf .expo && rm -rf node_modules/.cache && rm -rf dist && node build-simple.js"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  BABEL_ENV = "production"
  SKIP_PREFLIGHT_CHECK = "true"
  EXPO_USE_FAST_RESOLVER = "true"
  EXPO_NO_DOTENV = "1"
  EXPO_CLEAR_CACHE = "true"
  EXPO_PLATFORM = "web"
  EXPO_PUBLIC_USE_STATIC = "true"
  EXPO_NO_METRO_LAZY = "1"
  EXPO_NO_FLIPPER = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200